## We can test the action from within the action itself

name: Integration Test
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
env:
  IMAGE_TAG: '3.11-0ccdae'
  REPOSITORY: 'rzsoftware/redzone-deployer'
  EXPECTED_VULNERABILITIES: '2'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Evaluate Image Scan
        id: ecr-scan-image
        continue-on-error: true
        uses: kwalsh-rz/github-action-ecr-scan-test@main
        with:
          awsRegion: us-east-1
          awsAccessKey: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          imageTag: ${{ env.IMAGE_TAG }}
          repository: ${{ env.REPOSITORY }}
          failThreshold: high
          ignoreList: CVE-2022-1234,CVE-2022-4321
      - name: Check outputs
        id: check-outputs
        if: steps.ecr-scan-image.outcome == 'failure'
        run: |
          test "${{ steps.ecr-scan-image.outputs.vulnerabilities }}" == "${{ env.EXPECTED_VULNERABILITIES }}"
      - uses: actions/checkout@v3
        with:
          repository: "kwalsh-rz/github-action-ecr-scan-test"
          token: "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"
          path: github-action
      - name: Evaluate Image Scan
        id: ecr-scan-image2
        continue-on-error: true
        uses: ./github-action
        with:
          awsRegion: us-east-1
          awsAccessKey: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          imageTag: ${{ env.IMAGE_TAG }}
          repository: ${{ env.REPOSITORY }}
          failThreshold: high
          ignoreList: CVE-2022-1234,CVE-2022-4321
      - name: Check outputs
        id: check-outputs2
        if: steps.ecr-scan-image2.outcome == 'failure'
        run: |
          test "${{ steps.ecr-scan-image2.outputs.vulnerabilities }}" == "${{ env.EXPECTED_VULNERABILITIES }}"
